# Site settings
source: app
title: DylanMoriarty.github.io
safe:           false
source:         app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false 

syntax_highlighter: rouge

baseurl: ""

collections:
  dailies:
    output: true
